version: "3.3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - tokka-db:/var/lib/mysql
  nats:
    image: nats:latest
    ports:
      - "${NATS_PORT}:4222"
    expose:
      - ${NATS_PORT}
volumes:
  tokka-db:
